### ISSUE TITLE
Cannot index promise using dictionary keys

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#1023]
If a job function returns a dictionary, the promise cannot be indexed using a dictionary key: i.e.   `bqsr.rv('bam')`, but indexing a tuple or list works fine: `bqsr.rv(1)`.

I'll try and get a code example and stack trace up when I have time.

**Comment by hannes-ucsc** [comment]
This I would call an enhancement because `rv(index)` was only meant to compliment Python's tuple return feature. While working on this, we might want to extend the mechanism to `rv(indices)` so you can deal with nested structures, too, as long as those data structures support the `[]` indexing operator.

**Comment by hannes-ucsc** [comment]
This is actually invalid because it already worked. It was fixed in 2fae8040f5e91b72b0effa87c15f2c43e796a46d, I believe.

However, I will use the opportunity to generalize rv() indexing.
