### ISSUE TITLE
Can FileStore.localTempDir cleanup be controlled by the --clean config flag?

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1060]
Currently, the directory returned by [`FileStore.getLocalTempDir`](https://github.com/BD2KGenomics/toil/blob/master/src/toil/fileStore.py#L132) is cleaned up at the end of each job. This is inconsistent with the behavior of the [--clean](https://github.com/BD2KGenomics/toil/blob/1ef0cfa72bf16c5bc2f8306d532825b1d8251664/src/toil/worker.py#L528) option and can make debugging more difficult. Is this intentional? Ideally, the `--clean` flag would control the behavior of both.

**Comment by hannes-ucsc** [comment]
We have `--cleanWorkDir` for that. I think we separated it because the association is mostly incidental when using singleMachine with file job store because then (and only then) do the job store and the work dir reside on the local file system. On a cluster, you might want to keep the AWS job store, but clean up the worker's work dirs. I'm open to rethinking that, though.

**Comment by fnothaft** [comment]
Oh, man! I can't believe that I mixed `--clean` and `--cleanWorkDir` up. That's my error. Let me close this.
