### ISSUE TITLE
Fix default resource attributes for JobFunctionWrappingJob

### ISSUE THREAD

**Issue by jpfeil** [BD2KGenomics/toil#1119]
We are now using JobFunctionWrappingJob resource attributes to configure function calls, but currently the resource attributes default to None when the job function is called. 

@cket

**Comment by hannes-ucsc** [comment]
This description is incomprehensible (to me).

**Comment by cket** [comment]
When using the default resource values, job.cores (or job.disk, job.memory) will == None within a JobFunctionWrappingJob. This is because the default resources values have not been assigned yet.

**Comment by hannes-ucsc** [comment]
Still don't get it. Is this a bug or an enhancement.

**Comment by cket** [comment]
This is a bug. If I'm understanding this problem correctly, job defined like this:
```
def exampleJob():
      assert job.cores is not None
...
...
with Toil(options) as toil:
    toil.start(job.wrapJobFn(exampleJob))
```
will fail that assertion despite the fact that the default 'cores' value should be 1 (2? at least not None). 

This was discovered because @jvivian did some pipeline refactoring and is now modifying tool resource settings by referring to job.cores. Before that he was passing a separate job parameter 'numCores' to pass to the tools, which explains why we haven't come across this bug before. 

We should set the default values for these resources earlier on so this doesn't happen. The current work around is to explicitly set the jobs resource values and not rely on the default. @jvivian @jpfeil can you confirm?

**Comment by hannes-ucsc** [comment]
Now I get it. Thanks, @cket.
