### ISSUE TITLE
Toil appliance must start docker after mounting volumes

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1230]
@cket and I ran into this bug this afternoon when testing out the autoscaler. On machines with multiple ephemeral volumes, the Toil appliance JBODs the volumes together and mounts them to `/var/lib/docker`, `/var/lib/toil`, etc. If this happens after the Docker daemon launches, docker fails sporadically when writing to `/var/lib/docker`, and the Toil appliance does an infinite failure loop.

**Comment by hannes-ucsc** [comment]
> the Toil appliance JBODs the volumes together

It's not the appliance that does this, it's the VM if I recall correctly.

We ran into this with cgcloud. The workaround was quite involved because you have to move the contents of /var/lib/docker into the new location and moving it with rsync or cp was infeasibly slow. I think that's because /var/lib/docker contains sparse files or stuff like that. Tarring it up and untarring it into the new location worked much better. See cgcloud's DockerBox. I think I briefly mentioned all of this to @cket a while ago.

**Comment by fnothaft** [comment]
>> the Toil appliance JBODs the volumes together
>
> It's not the appliance that does this, it's the VM if I recall correctly.

Agreed; I misspoke.

@cket has a patch that cleans this up (see https://github.com/BD2KGenomics/toil/tree/issues/1230-docker-container-race) that appears to work from some overnight testing.
