### ISSUE TITLE
How does Toil interact with Kubernetes?

### ISSUE THREAD

**Issue by laserson** [BD2KGenomics/toil#1393]

**Comment by cket** [comment]
@laserson I'm not sure what is being asked - we have an Apache Mesos batch system implementation but nothing involving Kubernetes . Feel free to reopen with clarification if that doesn't answer your question.

**Comment by laserson** [comment]
Apologies for not being clearer (though I am just learning some of these tools so I don't necessarily know how they all fit in together).  According to the docs, Toil uses CGCloud to provision clusters on the cloud.  Could it instead use Kubernetes for this?

**Comment by cket** [comment]
I see - I'm not very familiar with Kubernetes so I'm not sure what its capabilities are. You might be able to set up Kubernetes to provision a Toil cluster but I would recommend using CGCloud since that set up is done for you. Alternatively the next release of Toil will include an autoscaling feature that will allow the use a 'native' Toil provisioner in addition to CGCloud.

**Comment by laserson** [comment]
Interesting.  I am interested in Kubernetes because it seems to be the new hotness for managing clusters and especially for coordinating containers.  It also works with all the major clouds, AFAIK.

**Comment by gourneau** [comment]
I know this a closed issue. I just wanted to mention that the new version of Kubernetes 1.5 now supports batch jobs https://kubernetes.io/docs/user-guide/jobs/

I have no idea how difficult it would be to and Kubernetes support to toil, but I think it would be a neat feature :)

Thanks!

**Comment by rokroskar** [comment]
Apologies for commenting on such an old issue -- however, with the current dominance of kubernetes in the cloud orchestration world, are there are any plans to support it in toil?
