### ISSUE TITLE
Leaf jobs finish and the leader never hears about it, waits forever

### ISSUE THREAD

**Issue by ArtRand** [BD2KGenomics/toil#1450]
Hello Toil team, 

I'm experiencing a problem where a job ([this one](https://github.com/ArtRand/marginAlign/blob/toil_dev/src/margin/toil/variantCaller.py#L23)) will finish but the leader will not know about it. Thousands of these jobs get issued and usually 1-3 of them will stay RUNNING while the PID on the host is gone. Obviously the workflow cannot continue, so everything just waits. 

If I kill the workflow and then restart it, the jobs will be reissued, and most of the time they will finish and the whole thing will carry on. At this point I've become accustomed to just watching Mesos for the end of this step in the workflow then nudging it through this awkward part and then everything is fine. 

I used to think the problem stemmed from jobs failing, but I no longer think this is the case. I can reproduce the issue on smaller datasets, but it's completely sporadic. If I had to guess right now I think the job store becomes inconsistent or partitioned on some way.  

Is there a per-job 'time-out' parameter? That way I could just give the job a designated amount of time, say 10 mins, and after that it's killed and re-issused a given number of tries. 

Happy to stop by this week to show you what's going on. 

Thanks!

Art

**Comment by cket** [comment]
I've been thinking about this - I remember you saying you SSH-ed onto the worker nodes and saw there was no Toil process running, correct? I think this might be a Mesos issue. It's up to the batch system to report job status, so if mesos isn't doing that we could end up in this situation. Do you know what version of mesos and Toil you're using?

**Comment by ArtRand** [comment]
Hello CJ,

Mesos 0.25.1
Toil 3.5.0a1.dev325

Hope that helps,

A

**Comment by cket** [comment]
@ArtRand thanks - it's also very possible that it is a problem with the job/docker container that is being run. I've seen this behavior when a node's disk fills to 100%, is that what is happening here? 

When you see this next I would double check if `ps aux` shows toil_workers and/or docker containers running on the worker. Running `docker ps -a` to list stopped containers has also been helpful for me in the past -- since the containers are supposed to be deleted after every job, any containers listed there are indicative of a problem.

**Comment by ArtRand** [comment]
I’ve checked the disk, it’s has plenty of space. I use the command line
option --workDir=/var/lib/toil and they usually only use up ~5% of the
available space. I’ll run the commands you suggested and get back to you
with the results.

Thanks!

A
​

**Comment by ArtRand** [comment]
It may be worth mentioning that I am using the toil-box base image and
upgrading toil after the fact. I am also using toil-lib==1.2.0a1.dev139.
​

**Comment by ArtRand** [comment]
Ok, so I collected the report from ps and docker ps -a (see attached). I
was able to isolate one job that had died on one node, but it’s typical for
this to happen to ~5 jobs on any number of nodes. It appears that the
docker images are not being deleted (which is the default in docker_call I
believe) and there is a ‘sleeping’ toil-worker process. What do you think?
​

**Comment by cket** [comment]
Ok, that is consistent with what I've seen before when we run out of storage. Even if you're sure the workDir isn't full, I would check the other volumes via `df -h` to see if any filesystems are at capacity - the root volume can be tiny on some EC2 instances and if any processes (like Docker) are writing to it they can hang everything else. 

If it turns out that isn't happening, we should probably meet in person to start debugging it more thoroughly.

**Comment by ArtRand** [comment]
Yeah, I checked that, this is from the node with the dead job:

Filesystem      Size  Used Avail Use% Mounted on
udev             61G   12K   61G   1% /dev
tmpfs            13G  364K   13G   1% /run
/dev/xvda1      9.8G  2.0G  7.3G  21% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none             61G     0   61G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb       296G  2.7G  278G   1% /mnt/ephemeral

Looks ok. I do ‘preload’ my images on my AMI, do you think that’s the
problem?

I can meet tomorrow AM or I have a meeting with John V Wednesday afternoon
so I’ll be there already if you want to chat. Thanks for all the help!

A
​

**Comment by cket** [comment]
Wednesday works for me!

**Comment by cket** [comment]
@ArtRand after our talk I tried to figure out why the Toil worker would be sleeping, and I think it's because Python is blocking while it waits for the zombie Docker container to finish. The more I think about it, the more it seems like a non-deterministic failure in the container. 

I think the other problems you saw with the other non-docker job is probably a different issue that we should consider unrelated right now.

**Comment by ArtRand** [comment]
I agree, I'll keep digging and try and sure up that container too.
