### ISSUE TITLE
Autoscaling provisioner is wimpy

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1874]
I am running a run on AWS with autoscaling with a max of 4 preemptable nodes. It spins up one worker node, and that node gets filled up by a job:

<img width="307" alt="screen shot 2017-09-12 at 6 04 25 pm" src="https://user-images.githubusercontent.com/5062495/30317516-47707d5a-97e5-11e7-84b8-19a33315704a.png">

It then sits around not making any more nodes for the other jobs, printing this:

```
ip-172-31-20-197.us-west-2.compute.internal 2017-09-12 09:03:37,163 preemptable-scaler INFO toil.provisioners.clusterScaler: Estimating that cluster needs 1 preemptable nodes of shape _Shape(wallTime=3600, memory=261993005056, cores=32, disk=687194767360), from current size of 1, given a queue size of 7, the number of jobs per node estimated to be 4.33333333333, an alpha parameter of 0.8 and a run-time length correction of 1.0.
ip-172-31-20-197.us-west-2.compute.internal 2017-09-12 09:04:08,277 preemptable-scaler INFO toil.provisioners.clusterScaler: Estimating that cluster needs 1 preemptable nodes of shape _Shape(wallTime=3600, memory=261993005056, cores=32, disk=687194767360), from current size of 1, given a queue size of 7, the number of jobs per node estimated to be 4.33333333333, an alpha parameter of 0.8 and a run-time length correction of 1.0.
ip-172-31-20-197.us-west-2.compute.internal 2017-09-12 09:04:37,628 preemptable-scaler INFO toil.provisioners.clusterScaler: Estimating that cluster needs 1 preemptable nodes of shape _Shape(wallTime=3600, memory=261993005056, cores=32, disk=687194767360), from current size of 1, given a queue size of 7, the number of jobs per node estimated to be 4.33333333333, an alpha parameter of 0.8 and a run-time length correction of 1.0.
```

It ought to make another node, at least. Is there some kind of aggressiveness parameter I should tune?

**Comment by adamnovak** [comment]
OK it finally did spin up a node; maybe it's that my scaling interval is too long; I don't want to wait 30 minutes while one measly node works on my workflow.

**Comment by joelarmstrong** [comment]
It's because the autoscaler (in master branch) is based on *completed* jobs, not on queued jobs. So the autoscaler judges how many nodes to spin up based on the runtime of the average recently completed job. This means it can take quite a long time to adjust when starting out, or if new jobs suddenly take much more/much less time than recent jobs.

Not sure why it was written that way, exactly, but there's already an issue or two about this. #1744 contains fixes for this, but it may be another week or two till it's battle-tested and merged.
