### ISSUE TITLE
Clearly define and implement the semantics of global file store

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#1887]
The semantics should be documented clearly in the API.

The motivation for this is to make global file store behavior clear and as consistent and efficient as possible across different files stores and with or without caching.

The suggest public semantics are:

- With readGlobalFile mutable=False
  - File maybe either copied, hard-linked or symbolic-linked to the jobStore.  The exact method depends on the jobStore implementation.
  - The jobStore file may be set to write-protected.  This behavior is not guaranteed and depends on the jobStore implementation.  For instance, on a shared file system jobStore, symbolic links will be created to the global file location, however the file permissions will not be changed.
  - The behavior of modifying a file marked as immutable is undefined.  It may result if crashes, incorrect results or data corruption.  Do not do this.

- With readGlobalFile mutable=True
  - The file will be copied to the jobStore
  - The file permissions will be set to writable.

The above semantics are maintained with cached enabled or disabled.

TO DO:
  - Defined semantics of file naming, including user name, along with rationale.
  - Support directories of files as first class file store objects.
  - readGlobalFile default for mutable should be `False', not `None.
  - Do not reference to internal modules, e.g. cache (bool) – Described in toil.fileStore.CachingFileStore.readGlobalFile()

**Comment by diekhans** [comment]
related to #1846

**Comment by joelarmstrong** [comment]
I totally agree with all of this. I think moving to symlinks for the FileJobStore should be a closely related effort, because it would be useful on most HPC systems (right now it attempts to hard-link, but since it tries to hardlink to a dir in $TMP, it's not really that useful for most setups).

Re: the cache flag for readGlobalFile, I see what you mean, but I think we can't get rid of that keyword argument anytime soon. Removing it would break backward compatibility. (PS: Do we have a procedure for breaking/maintaining backward compatibility? Do we adhere to [semver](http://semver.org/) or do we want to be a little looser?)

**Comment by diekhans** [comment]
Sorry to be unclear, I was only complain about the documentation
for the cache flag, not wanting to remove it.

Semantic versioning is a good thing.
