### ISSUE TITLE
Toil uses subprocess in inconsistent, risky, and sometimes buggy ways

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#2039]
After Joel discovered that the gridengine does not check subprocess status, leaving zombies around and possibly incorrectly interpreting results.  This is also seen in lsf. Several places use shell=True, which is full of landmines and is explicitly warned against in the python documentation. 

A review of the use of subprocess is warranted.  Creating common, higher level functions to interface to process would help ensure consistent and robust process creation, consistent logging, and remove redundant code.

Process creation is much trickier than it appears.

**Comment by joelarmstrong** [comment]
We should also consider using [subprocess32](https://github.com/google/python-subprocess32), which is a backport of the Py3 subprocess module. It fixes a lot of race conditions that are (to my knowledge) still present in the 2.7 branch.

**Comment by DailyDreaming** [comment]
I'll make a PR for subprocess32 because that sounds like a really good idea and a couple of `shell=True` statements that I refactored in `template_version.py`.  Overall, after talking with Mark, tearing out the shell=True stuff seems like a lower priority and something we should handle as we go, unless any in particular seem to stand out as risky (many don't interpret user input and so don't seem at risk from that particular vulnerability).

**Comment by ejacox** [comment]
Fixed in #2072.
