### ISSUE TITLE
log_config parameter to apiDockerCall improperly documented

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2127]
The docstring at https://github.com/BD2KGenomics/toil/blob/8abd2826f45f1f79984e39ce2ab3fa8b4d112bd9/src/toil/lib/docker.py#L245 says `log_config` should be a string, but it is passed right on to the Docker API, which according to https://docker-py.readthedocs.io/en/stable/containers.html expects log_config to be a dict.

The documentation for Toil should say that log_config should be a dict.

**Comment by DailyDreaming** [comment]
@adamnovak That's a fair argument.  The original `subprocessDockerCall()` is mainly used by @glennhickey (who recently added stderr) and @jvivian as far as I'm aware.  The API was implemented due to better error messages, a cleaner interface, and having features that allowed for easier inputs for WDL support.

The docstring and unused `stderr` + `dockerParameters` removal are a quick fix.  `dockerParameters` is completely replaced by using the kwargs.  `stderr` is not implemented unfortunately.

Eventually I'd like to address the `stdout` and `stderr` kwargs in a similar way, which would likely be done with the `attach(container, stdout=True, stderr=True, stream=True, logs=False)` API call to the container documented here: http://docker-py.readthedocs.io/en/stable/api.html as I believe this use-case is the only current difference in terms of functionality.
