### ISSUE TITLE
Options are overwritten on restart

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#217]
When restarting a toil workflow the all options are overwritten with what the user specifies + defaults. It would be preferable if only the options that the user specifies be overwritten

**Comment by hannes-ucsc** [comment]
I would derive the option defaults from the config object:
```
parser.add_argument( '--foo', default=config['foo'] )
```
That way a user can run `toilResume --help` and the printed defaults would be correct. In the non-resume case the config object would be initialized with the defaults, otherwise it would be read from the job store.

Whatever you end up doing, the default values should be mentioned exactly once in the code.

**Comment by benedictpaten** [comment]
I agree, this would be a great way to do it. I revised it so now there is this option "useExistingOptions", but your suggestion is much better and would avoid this.
