### ISSUE TITLE
Upload final output files to AWS S3/Azure Blob/Google Cloud Storage

### ISSUE THREAD

**Issue by mwiens91** [BD2KGenomics/toil#2241]
Currently (and please correct me if I'm wrong) Toil will spit out its
output files at the head node where you run a workflow. This is fine for
many cases, but sometimes it's more convenient to have all of the output
files in cloud storage.

One way of facilitating this is to add a runtime argument which lets us
specify an output file endpoint.

An implementation of this, written by @Irrationone, which works for
(only) CWL and Azure can be seen here:

https://github.com/BD2KGenomics/toil/compare/master...Irrationone:304682394b5687a88f1f48415e2e462138e83e76

This changeset makes a new object, a "final job store", which is another
job store which essentially represents the final storage destination for
the output files.

The downside of this is that it conflates a final storage destination
with a job store, which may not be desired; and that the final job store
contains much more functionality than is necessary for its purpose.

The upside of making the final storage destination another job store is
that it only requires adding in minimal code.

Anyway, any discussion on how to implement will be much appreciated.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-164)
┆Issue Number: TOIL-164

**Comment by DailyDreaming** [comment]
`fileStore.exportFile(p.resolved[7:], destUrl)` could place the files at any `destUrl`.  I think this could be a useful option for cwl (users can use the `fileStore.exportFile()` in their script directly with native python), though I think the exporting to any generic user-specified bucket rather than a jobstore would be preferable (especially if wanting to export to a bucket that is already being used for other things).
