### ISSUE TITLE
Use nosetest as a test runner

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#250]

**Comment by hannes-ucsc** [comment]
Changed my mind. Using py.test instead of nose. Now you get this:

http://jenkins.cgcloud.info/job/toil/218/testReport/

Plus the output of each test is isolated. Some test output may still leak to the general 

Individual tests need to be run like this:

py.test src/toil/test/src/resourceTest.py

after making sure that py.test is installed via

pip install --user pytest==2.7.2

If you've alread run make test, there's a good chance that py.test is already installed because by.test is declared as a test dependency in setup.py.

**Comment by hannes-ucsc** [comment]
The last paragraph is factually wrong.
