### ISSUE TITLE
Make jobTree pip-installable

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#34]

**Comment by jvivian** [comment]
Transitioned imports from sonLib to jobTree.lib.bioio.   Surrounded unresolved imports with a try/except until benedict or myself prunes out the unnecessary methods. 
https://github.com/BD2KGenomics/jobTree/commit/762945227c3fb35d9c9bcc1cde39858aa9716c25

**Comment by hannes-ucsc** [comment]
https://pythonhosted.org/setuptools/setuptools.html

is the authoritative reference to setuptools.

**Comment by jvivian** [comment]
Package Structure will change as follows after moratorium is called:

jobTree
├── src
│            └── jobTree                
│                                 └── init.py
  |                                  └── batchSystems
  |                                  └── All other contents of jobTree and jobTree/src
└── setup.py
└── README.md
└── Makefile
└── LICENSE.txt
└── .gitignore

**Comment by hannes-ucsc** [comment]
Looks good. We'll have a test package per main package with tests for  code in the that main package rather than gathering all tests in a top-level test package. I'm not asking for this because I think it is necessarily a better approach but I found that this layout works better for setuptools.

Secondly, I did a trial run of a project deployment to PyPI and it was straight-forward. We will register a 'generic' cgl-ucsc user using our cgc mailing list for the email address. We'll share those credentials and ultimately use them to deploy to PyPI from Jenkins CI.

**Comment by hannes-ucsc** [comment]
We will soon be blocked on this.  We need 1) deployment to PyPI and 2) an additional entry point declaration for the mesos executor before we can close this issue.

**Comment by jvivian** [comment]
Can others test?    "pip install jobTree"

**Comment by hannes-ucsc** [comment]
If you do, do it in a virtualenv.

Also, "setup.py develop" needs to be tested.

On Thu, Jul 2, 2015 at 9:51 AM, John Vivian <notifications@github.com>
wrote:

> Can others test? "pip install jobTree"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/34#issuecomment-118091221>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by jvivian** [comment]
I run into the same problem with:    
    
    python setup.py develop --user

as I did with:

    python setup.py install --user

and 

    easy_install jobTree

It looks for a setup.py inside of mesos.interface and can't find it so errors.   This doesn't seem to be an issue when installing via pip.   

A bug that needs fixing is running "pip uninstall jobTree" gives an error message:
    
    IOError: [Errno 2] No such file or directory: '/usr/local/bin/jobtreekill'

It successfully uninstalls the rest of jobTree, but errors here because of a typo in the casing.  "/usr/local/bin/jobTreeKill" exists.  The naming in setup.py is correct, so I'm unsure where it's pulling the all lowercase name from, looking into it now.

**Comment by hannes-ucsc** [comment]
Assigning to CJ

**Comment by jvivian** [comment]
CJ is currently trying to replicate the errors i had with python setup.py install/develop. 

But since Hannes mentioned we "need python setup.py develop",  I thought it worth mentioning:

**"Editable" installs [pip install -e] are fundamentally "setuptools develop mode" installs.** 
https://pip.pypa.io/en/latest/reference/pip_install.html#editable-installs

**Comment by cket** [comment]
pip install jobtree worked 
pip install -e path/to/jobTree worked with and without mesos.native 
pip uninstall jobtree worked
python setup develop gave this error:

error: Couldn't find a setup script in /tmp/easy_install-CnBBR9/mesos.interface-0.22.1.2.linux-x86_64.tar.gz

**Comment by cket** [comment]
It also looks like psutil requires python-dev. I pip installed jobtree on a mesos ec2 instance and when it tried to pip install psutil as a dependency, it failed looking for python.h. After googling, I found that this means that the box did not have python-dev installed. Installing this fixed the install problem.

**Comment by cket** [comment]
I made some modifications to setup.py in the dag-rebased branch. Under the previous logic, if mesos.native and mesos.interface were installed then mesos.inteface would be uninstalled and then re-pip-installed. If (like in the cgcloud role) mesos.native and mesos.inteface had been installed via an egg, pip installing mesos.inteface puts the interface into a different module also named mesos. This caused import problems, since python only looks into the first module of a given name and ignores the rest.
