### ISSUE TITLE
Run a 100 node t2.micro cluster with dummy workload

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#350]

**Comment by cket** [comment]
I just ran this with a script that only creates children jobs, no other tasks involved. In total it had 5,200 jobs and finished in ~5 minutes. The first time an internal AWS error caused one job to fail, but all succeeded on the second try. I will create a follow up issue about the AWS error so that we can retry when it occurs instead of give up.

**Comment by hannes-ucsc** [comment]
Run 99+1 test with beefy master
