### ISSUE TITLE
Use Nonce to encrypt files

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#406]
Ted is worried that UUID and master key together do not have enough entropy.  

A nonce is similar to salting hashed passwords. So

nonce = random_bytes(32)
per_file_key = sha1( master_key + uuid + nonce )
return per_file_key, nonce

The nonce will then have to be stored either as metadata alongside the file or in a database together with the uuid. It is not secret.

**Comment by hannes-ucsc** [comment]
Joel to research the exploitability.

**Comment by joelarmstrong** [comment]
In a nutshell, we should keep doing what we're doing, without a nonce, but use HMAC-SHA256 rather than SHA-256 to derive the key.

[NIST recommendations](http://csrc.nist.gov/publications/nistpubs/800-108/sp800-108.pdf)

Section 5.1 is a generalization of what we're doing here--note that this reduces to our use case exactly (trivially replacing their several public constants "0 || Label || 0x00 || Context || 256" with our single public constant) since we have a key length equal to the hash length. But we use SHA-256 as the PRF, whereas they recommend an HMAC version.

It's also equivalent to the HKDF-expand function described [here](https://eprint.iacr.org/2010/264.pdf).

This protects us from length-extension attacks in cases where one filename is a prefix of another.

**Comment by hannes-ucsc** [comment]
Is it correct to say that because the master key was generated using a cryptographically secure pseudo-random function, we don't need a nonce?

**Comment by joelarmstrong** [comment]
I think that's the correct rationale, but I'm not a cryptographer. HKDF actually has an optional stage which includes a nonce (although they call it a salt), which is meant to be used if the key is not cryptographically secure.

My thinking is that producing a 256-bit key by mixing in more entropy to a 256-bit truly random key can't increase its entropy, by definition.

The HKDF RFC says, in describing the difference between the "extract" (with salt/nonce) and "expand" stages:
```
In some applications, the input may already be a
   good pseudorandom key; in these cases, the "extract" stage is not
   necessary, and the "expand" part can be used alone.
```

**Comment by hannes-ucsc** [comment]
In this today's scrum, @joelarmstrong suggested that the current naive `sha1(key+url)` algo might be vulnerable to an extension attack. We agreed that we want to implement the HMAC without Nonce. Ultimately, this should go into bd2k-python-lib such that John can use it in his Toil user scripts.

**Comment by hannes-ucsc** [comment]
Obsoleted by BD2KGenomics/toil-scripts#34
