### ISSUE TITLE
Refuse install with mesos extra if mesos.native is missing

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#420]
I managed to install Toil with the `mesos` and `azure` extras, but now I am trying to use the `mesos` batch system, and it can't import the `mesos.native` module.

Sure enough, it's not installed. The Toil `setup.py` file lists only a dependency on `mesos.interface`, and none on `mesos.native`.

Since mesos.native can't be installed from PyPI, Toil should refuse to install with the mesos extra unless the correct mesos.native version is already installed.

**Comment by hannes-ucsc** [comment]
CJ, I want you to take a look at this. I think in `setup.py` we should check that mesos.native can be imported. The hard part will be to do this only if `mesos` extra was requested.

**Comment by hannes-ucsc** [comment]
This patch works for pip install:

```
Index: setup.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- setup.py	(revision 05aaeadb75badf6d2c6ecb94954ee6651e58c7bc)
+++ setup.py	(revision )
@@ -65,6 +65,23 @@
         sys.exit( errno )
 
 
-kwargs[ 'cmdclass' ] = { 'test': PyTest }
+from setuptools.command.install import install
+
+
+class MyInstall(install):
+    def run(self):
+        try:
+            import mesos.interface
+        except ImportError:
+            pass
+        else:
+            try:
+                import mesos.native
+            except ImportError:
+                raise RuntimeError("mesos.native is missing blah blah")
+
+        return install.run(self)
+
+kwargs[ 'cmdclass' ] = { 'test': PyTest, 'install': MyInstall }
 
 setup( **kwargs )
```

**Comment by adamnovak** [comment]
What if an incorrect version of mesos.native is installed? The fancy python
entry point stuff will check that dependencies are satisfied by the
specified versions of modules before starting your code. I observed my
workers failing to start on Mesos once because the entry point code saw
mesos.native 0.23 installed, and bailed because the mesos.native==0.22
dependency wasn't satisfied.

It might make sense to check the version here, and not just the existence.

-Adam

**Comment by hannes-ucsc** [comment]
This works for me to determine the currently installed version:

```
pkg_resources.get_distribution('mesos.native').version
```

**Comment by hannes-ucsc** [comment]
Unfortunately, by the time setup.py is invoked, it is almost impossible to interrogate what extras were specified on the pip command line. This is because pip invokes setup.py without passing that information along. It can be done, of course, by interrogating the parent process' command line but I am hesitant to implement it.

Once installed, it is also impossible to determine the requested extras. I don't think pip or setuptools even persists that information.

In fact, PR #520 will remove the dependency on mesos.interface because that package is installed by the native Mesos package (I checked the .deb and the Homebrew recipe) or when installing from the Mesos source.
