### ISSUE TITLE
Incorrect catch for missing .toilAzureConfig

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#421]
The Azure job store tries to give a useful message when it can't read your .toilAzureConfig for the key for the Azure job store storage account. However, it is looking for a `NoOptionError`, and if the entire file is missing instead a `NoSectionError` is raised, producing an error like this:

```


DEBUG:toil.batchSystems.mesos.executor:Starting executor
I0924 22:47:08.587648 43191 exec.cpp:132] Version: 0.22.0
I0924 22:47:08.592193 43192 exec.cpp:206] Executor registered on slave 20150924-214557-83886090-5050-44087-S8
INFO:toil.batchSystems.mesos.executor:Registered with framework
DEBUG:toil.batchSystems.mesos.executor:Running task 0
DEBUG:toil.batchSystems.mesos.executor:Sending status update ...
DEBUG:toil.batchSystems.mesos.executor:Sent status update
DEBUG:toil.batchSystems.mesos.executor:Invoking command: '/usr/bin/python2.7 -E /usr/local/lib/python2.7/dist-packages/toil/worker.py azure:hgvm:tree2 683b1010_55c3_4978_a7e7_853f17ed1803'
DEBUG:toil.batchSystems.mesos.executor:Sent stats message
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 408, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 89, in main
    jobStore = loadJobStore(jobStoreString)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 366, in loadJobStore
    return AzureJobStore( account, namePrefix, config=config )
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/azureJobStore.py", line 78, in __init__
    account_key = _fetchAzureAccountKey(accountName)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/azureJobStore.py", line 63, in _fetchAzureAccountKey
    return configParser.get('AzureStorageCredentials', accountName)
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'AzureStorageCredentials'
DEBUG:toil.batchSystems.mesos.executor:Sending status update ...
DEBUG:toil.batchSystems.mesos.executor:Sent status update
I0924 22:47:09.738494 43200 exec.cpp:379] Executor asked to shutdown
CRITICAL:toil.batchSystems.mesos.executor:Shutting down executor...
CRITICAL:toil.batchSystems.mesos.executor:Executor shut down
```

I'm observing this on my Mesos slave nodes, which don't share a home directory with my master.

Additionally, although I have set `AZURE_ACCOUNT_KEY` on the master, it doesn't seem to be propagating to the slaves to prevent this (perhaps because the environment loading and saving happens in the worker, using stuff stored in the job store?).

**Comment by joelarmstrong** [comment]
Whoops, I read the configparser docs wrong. Will fix. Thanks.

Yes, you would need to set AZURE_ACCOUNT_KEY manually somehow on each of the workers, since the environment is read from the job store itself. That's more or less unavoidable. I'd suggest baking the credentials file into your slave node images--similar to the .boto file on AWS.

**Comment by joelarmstrong** [comment]
Although, alternatively, maybe the mesos batch system could take care of propagating the environment automatically? I think parasol, at least, shuffles around your environment for you.

**Comment by adamnovak** [comment]
I'm trying to hack the functionality into the mesos batch system right now.

What should really happen is that some job-store-specific internal state for the job store should be propagated to the nodes, so they can connect back to the job store. It should be able to read keys or whatever out of the config on the master and send them to the workers through the batch system (somehow).

**Comment by hannes-ucsc** [comment]
We use IAM roles on EC2 so there should be no need for a .boto on an EC2 instance. IAM roles allow  you authorize code running on an EC2 instance to access AWS resources.  Try to see if there is a similar mechanism on Azure. 

If that is not possible, we need an AbstractBatchSystem.setEnv(name,value) method.  Any variable set via that method would be guaranteed to be set on a worker node before worker.py is actually invoked.

**Comment by adamnovak** [comment]
Keep in mind that you might want to use, say, the Amazon job store from an
Azure compute instance. Maybe you're doing some crazy multi-cloud thing?

Also, where/when would the JobStore call setEnv on the batch system in
order to persist its configuration to the nodes?

**Comment by joelarmstrong** [comment]
Boto can use environment variables for AWS credentials too, so it'd still work, but maybe not ideal to have to set that many variables.

Are we eventually intending to send encryption keys to the nodes as well (presumably over scp)? If so, maybe the credential files could be copied along with the keys. I don't think sending the keys through the batch system would be a good idea.

**Comment by hannes-ucsc** [comment]
> Keep in mind that you might want to use, say, the Amazon job store from an
> Azure compute instance. Maybe you're doing some crazy multi-cloud thing?

That's a less likely use case. IAM roles is an elegant mechanism since it doesn't involve distributing credentials. If Azure has the equivalent, I would want to use it.

> Also, where/when would the JobStore call setEnv on the batch system in
> order to persist its configuration to the nodes?

There already is a case where the batch system and the job store interact. However it's in the other direction. The batch system asks the job store for a public URL to the user script. That's how your user script gets to each instance. Most of this is implemented in resource.py.

To answer your question, the environment entries added via setEnv could be embedded in the worker.py command lines. They are being executed via `subprocess.check_call( ..., shell=True )` so prepending env entries as in `FOO=BAR python worker.py ...` is an option. But it is insecure to expose a secret that prominently. I am sure it would show up in all kinds of logs. 

You probably already noticed, but Mesos has a way to send arbitrary data via the task.data field. We could pass the env entries that way. I'd be ok with _implementing_ setEnv() only in the Mesos batch system. The other batch systems are really only useable with a shared FS anyway since they rely on the user script being stored on the shared FS. Only the Mesos batch system currently uses the resource mechanism I mentioned earlier. 

@joelarmstrong `cgcloud start-toil-cluster` has a `--shared-dir` option which we use to distribute the S3 SSE-C encryption key to each worker. This is preferable to baking the key file into the image. But encryption is optional. I'd hesitate to use this mechanism for files that are mandatory for running Toil on Azure. So we have the following candidate solutions:

1) Use equivalent of IAM roles
2) Embed in worker.py command line
3) Send via Mesos' task.data 
4) Bake into image
5) Distribute at cluster start-up time

Did I forget any?

**Comment by adamnovak** [comment]
It looks like the Azure concept is "Service Principals", which is a way to grant applications limited access to Azure (presumably, including enough access to retrieve a storage account API key). However, that still relies on the application itself having a password to authenticate itself to Azure.

Distributing the key at cluster start-up time (5) might work OK. What I have as my work-around right now is adding the environment to the task data (3), but that means your whole environment is serialized and deserialized twice: once for the worker, and once for the job itself.

**Comment by hannes-ucsc** [comment]
So I created #441 and #437 as follow ups to this issue. @joelarmstrong, once these two are addressed, is there anything else that needs to be done for this issue?
