### ISSUE TITLE
sortTest and utilsTest can hang indefinitely trying to restart

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#443]
This is not so worrying for interactive testing, but really annoying with Jenkins

**Comment by hannes-ucsc** [comment]
Agreed, we need to make the failure simulation deterministic. I had @cket try to do that by seeding the RNG but the problem is that every worker is its own processing and so seeding the RNG wouldn't work.

Maybe we could hash an input parameter like the sort range and fail the build if the hash is even.
