### ISSUE TITLE
Why does job.fileStore.writeGlobalFile() delete  local copy of file?

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#467]
I just updated to the latest build of toil (34) and writeGlobalFile now "safely removed (the local file) at the end of the job by placing it in a location returned by getLocalTempDir". This would not be acceptable if the user is running the  pipeline on on files not downloaded to a local temp dir but, from their original locations.

**Comment by benedictpaten** [comment]
You can solve this by first copying the file, although that some what defeats the purpose. I think instead we should have two methods, one which is writeAndReleaseGlobalFile(), which acts like the current method. Secondly, a method that blocks and is not asynchronous, which can be used when you need access to the file after you've copied it, or if it is a globally mounted file, as per Arjun's example.

**Comment by benedictpaten** [comment]
Hi Arjun, on reflection I  fixed this. Now (in my PR) if your file is not a path within the local temporary directory structure it will not be added to the cache (because doing so is complicated), and will not get deleted(!).

However, the write is still asynchronous, so if you want to modify it after this call you should make a copy or, if you prefer, I can add a blocking flag or blocking method which would do what the old function did.

**Comment by arkal** [comment]
Thanks Benedict. 

So if i have a job A that (say) aligns 2 fastqs to a bam and then a  job B that does mutation calling. If 
```
a = job.wrapJobFn(A)
b = job.wrapJobFn(B, a.rv())
a.addChild(B)

def A(job, ...)
   ...
   wgf_rv = writeGlobalFile(bamfile)
   return wgf_rv

def B(job, x, ...)
   readGlobalFile(x)
```

Does the readGlobalFile in B get affected by the asynchronous write?
