### ISSUE TITLE
Toil default cache size is too small

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#488]
The default 2.14G cache is too small for most purposes. Suggestion for enhancement could be to dynamically allocate it to 50%(or whatever fraction) of the free space on the volume that holds the localTempDir

```
import ctypes
import os
import platform
import sys

def get_free_space_mb(dirname):
    """Return folder/drive free space (in megabytes)."""
    if platform.system() == 'Windows':
        free_bytes = ctypes.c_ulonglong(0)
        ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(dirname), None, None, ctypes.pointer(free_bytes))
        return free_bytes.value / 1024 / 1024
    else:
        st = os.statvfs(dirname)
        return st.f_bavail * st.f_frsize / 1024 / 1024

cache_size = max(0.5*get_free_space(self. localTempDir), 2.14G)
```

Code was obtained from 

http://stackoverflow.com/questions/51658/cross-platform-space-remaining-on-volume-using-python

**Comment by arkal** [comment]
#486

**Comment by hannes-ucsc** [comment]
Looks got. We can safely delete the windows part since Toil does not support it. When computing the default value for the cache size,  the directory  where the cache will be created should be passed to the above function.

Beware that statvs is deprecated

https://docs.python.org/2/library/statvfs.html

As an alternative, checkout psutil which Toil already depends  on for Mesos.

**Comment by arkal** [comment]
i think ```--workDir``` is the cache location.  However, this will have to happen AFTER input arguments have been parsed since we cannot assume what folder the user will use for ```--workDir``` when the help is being generated and hence cannot print an accurate value in the default field.

**Comment by arkal** [comment]
So should we close this?

**Comment by benedictpaten** [comment]
To deal with the above problem Adam suggested with split the requested disk size into two (optionally). 

For a job let "diskRead" be the number of bytes the job will read from the job store. Let "diskWrite" be the number of bytes the job will write to the job store. diskRead + diskWrite = disk, where "disk" is the variable used to request disk space for a job.

If we make these two optional parameters, then the cache size setting is simply equal to diskRead.  I like this because it simplifies cache specification a lot.

If we do not insist these variables be specified, but simply assert that diskRead + diskWrite = disk, filling in missing values with defaults that satisfy these constraints then we get what we want. If only disk is specified then we should use an optional cache parameter, which by default would be small, because of the above risk highlighted above. 

If people like this solution I can implement it in an hour or so. Thoughts? There are definitely more elegant interfaces, but this is really simple and easy and requires very little extra implementation.

**Comment by hannes-ucsc** [comment]
I like it but I doubt it is going to be just an hour. It sounds more involved. We are still trying to get a release out ASAP. If you are ok pushing the release out until next week then I'd be ok including this.

**Comment by benedictpaten** [comment]
I have simplified it and pushed it into my PR for #500. I simply added a cache parameter to job. This equivalent to my proposal. The cache value must be smaller than the disk value, and is the number of bytes of the total disk ask used for caching. 

A smarter way to do this would be to have the file IDs accessed by the job be listed as parameters of the job, that way caching could be much smarter. For now this "hack" parameter will do.

I would favor getting my PR into the release, as it also fixes an important bug that Arjun found.
