### ISSUE TITLE
Port S3 job store to Ceph (connected to #724)

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#726]

**Comment by cket** [comment]
I don't think this is possible after my evaluations of Ceph. Closing.

**Comment by mr-c** [comment]
@cket Do you remember what the issue was, so I can see if Ceph would now be suitable? (2022 vs 2016)

**Comment by cket** [comment]
Yeah, I tried to run a very basic proof-of-concept job and our Ceph installation kept falling over due to the load. We tried some performance tuning and I don't believe we got it off the ground. A non-trivial job would have required much more throughput than what we were attempting so it didn't look feasible at the time, at least for our set up
