### ISSUE TITLE
Fix Promises return value

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#729]
Our group would like to broaden the scope of promises (e.g. return both a fileStoreID and file-size that can be resolved and used in the same function).

**Comment by hannes-ucsc** [comment]
We generalized this today to

```
ra=job.addChildFn(a, ...).rv()
rb=job.addChildFn(b, ...).rv()
job.addFollowOnFn(f,disk=PromisedRequirement(lambda ra_, rb_: 3 * ra_.size + 2 * rb_.size, ra, rb ))
```

where `a` and `b` are job functions that return an object whose `size` attribute contains the size of a produced file. The lambda gets the resolved promises and will be evaluated in a synthetic job that is inserted by addFollowOnFn into the DAG to precede f.  `PromisedRequirement` is a holder object for the lambda and the unresolved promises (`args`). The logic in `addFollowOnFn()` will resemble

```
if instanceof( disk, PromisedRequirement ):
   syn = self.addFollowOn( disk.lambda, disk.args )
   syn.addChild( child )
```

More convenience can be added if no extraction or aggregation happens on the resolved promises:

```
ra=job.addChildFn(a, ...).rv()
job.addFollowOnFn(f,disk=ra)
```

Since an unresolved promise is of a distinct type, this case can easily be detected.

@arjun weighed against this (rightfully so) but I am going to mention it because of the cool factor:

```
ra=job.addChildFn(a, ...).rv()
rb=job.addChildFn(b, ...).rv()
job.addFollowOnFn(f,disk=ra.size * 3 + rb.size * 2)
```

can be turned into the PromisedRequirement structure mentioned above by implementing __add__, __mul__ and __get__ on promise objects and PromisedRequirement.
