### ISSUE TITLE
toil clean does not delete job store buckets

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/toil#754]
I have 2 jobstore buckets that remain persistent after using toil clean, more recent buckets (created in the past week) were cleaned out fine as normal. The message suggests they may have already been deleted, though still present on the s3 dashboard. 

mesosbox@ip-172-31-6-148:~$ toil clean aws:us-west-2:plloyd-20160309
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.utils.toilClean:Parsed arguments
INFO:toil.utils.toilClean:Checking if we have files for toil
INFO:toil.utils.toilClean:The specified JobStore does not exist, it may have already been deleted

mesosbox@ip-172-31-6-148:~$ toil clean aws:us-west-2:plloyd-20160318
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.utils.toilClean:Parsed arguments
INFO:toil.utils.toilClean:Checking if we have files for toil
INFO:toil.utils.toilClean:The specified JobStore does not exist, it may have already been deleted

**Comment by cket** [comment]
Could this be because of s3's eventual consistency? You might want to try waiting a while and check in the buckets again later and see if they still show up. It's possible they really are deleted but the console doesn't reflect that fact yet.

**Comment by hannes-ucsc** [comment]
If what @cket suggests doesn't help, you may have attempted the clean earlier and it failed or you may have run the pipeline with `--clean=onsuccess` (or without `--clean` since `onsuccess` is the default) or the workflow may have failed in some weird way. Keep an eye on this, because the interesting bit would be the stacktrace of the first failed clean or the failed workflow.

**Comment by hannes-ucsc** [comment]
@dyollluap, please provide info and reopen if necessary.
