### ISSUE TITLE
Control-C doesn't stop a Toil script run completely

### ISSUE THREAD

**Issue by cmarkello** [BD2KGenomics/toil#877]
When using control-c to stop a toil script, it successfully shuts down the batch system and stops execution of commands, but doesn't exit the python script and relinquish control of the command prompt to the user. The python toil script child processes are still running.

However, I can clean the jobstore using the `toil clean <jobstore_name>` on an Azure storage account. And after manually killing the python toil child processes, I can rerun another instance of toil using the same jobstore name.

**Comment by hannes-ucsc** [comment]
My hunch is that this is caused by the use of multiprocessing.Process for the stats-and-logging aggregator in leader.py. multiprocessing is notorious for interfering with Ctrl-C. This is how s3am works around it:

https://github.com/BD2KGenomics/s3am/blob/9f7d35e18ce3a139a601d0ded94a0bfddc2a4858/src/s3am/operations.py#L1067

Anyhow, we might just eliminate Process and use Thread for this. Process is only needed on CPU-bound  tasks that are likely to content on the GIL. 

But first, we need to replicate the described behavior and see if the simple fix employed by s3am resolves the issue.
